# This workflow is triggered every time a change is pushed to any branches
# Github actions command reference: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
name: On Code Change (PR)

# The workflow could also be triggered on PRs
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  static-analysis:
    name: Static Analysis (linting, vulns)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jahia/jahia-modules-action/static-analysis@v2
        with:
          node_version: 18
          auditci_level: critical

  build:
    name: Build Javascript Module
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jahia/jahia-modules-action/build-step-javascript@v2

  publish:
    name: Publish Javacript Module to Maven repository
    needs: build
    runs-on: ubuntu-latest
    steps:           
        - uses: actions/checkout@v3
        - name: Publish javacript module
          uses: jahia/jahia-modules-action/publish-javascript@v2
          with:
            mvn_settings_filepath: .github/maven.settings.xml
            nexus_username: ${{ secrets.NEXUS_USERNAME }}
            nexus_password: ${{ secrets.NEXUS_PASSWORD }}
            module_path: ./
            node_version: 18