# This workflow is triggered every time a change is pushed to any branches
# Github actions command reference: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
name: On Code Change (PR)

# The workflow could also be triggered on PRs
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  static-analysis:
    name: Static Analysis (linting, vulns)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jahia/jahia-modules-action/static-analysis@v2
        with:
          node_version: 18
          auditci_level: critical

  build:
    name: Build Module
    runs-on: self-hosted
    needs: static-analysis
    env:
      NEXUS_INTERNAL_URL: ${{ secrets.NEXUS_INTERNAL_URL }}
    container:
      image: jahia/cimg-mvn-cache:ga_cimg_openjdk_8.0.312-node
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    steps:
      - uses: actions/checkout@v3
      - uses: jahia/jahia-modules-action/build-step-npm@v2

  npm-publish:
    name: Publish NPM Module to Maven repository
    runs-on: self-hosted
    needs: build
    steps:           
        - uses: jahia/jahia-modules-action/publish-npm@v2
          with: 
            nexus_username: ${{ inputs.nexus_username }}
            nexus_password: ${{ inputs.nexus_password }}
        - name: Publish tests package NPM
          uses: jahia/jahia-modules-action/publish-npm@v2
          with:
            mvn_settings_filepath: ${{ inputs.mvn_settings_filepath }}
            nexus_username: ${{ inputs.nexus_username }}
            nexus_password: ${{ inputs.nexus_password }}
            module_path: ./
            node_version: ${{ inputs.node_version }}
            tests_module_path: ./
